### ISSUE TITLE
Backend Login Test Case Failing when the password is incorrect

### ISSUE THREAD

**Issue by peeyush10234** [CSC510-Group-25/feature-hunt#111]
Backend Login Test Case Failing when the password is incorrect. User is able to login even when password is wrong

**Comment by snapcat** [comment]
https://github.com/CSC510-Group-25/feature-hunt/issues/112#issuecomment-955892803

**Comment by snapcat** [comment]
Discussion: https://github.com/CSC510-Group-25/feature-hunt/pull/119#issuecomment-968385183
