### ISSUE TITLE
login test case with wrong input not working

### ISSUE THREAD

**Issue by peeyush10234** [CSC510-Group-25/feature-hunt#112]
When giving wrong input into response, the expected status code was 500 but we got 200.

**Comment by snapcat** [comment]
Is this in the front end or back end? Which file(s) are you looking at?

**Comment by peeyush10234** [comment]
Backend, I am testing the backend login API, it is in the file backend-new/auth_controller.py

**Comment by snapcat** [comment]
#93 

https://github.com/CSC510-Group-25/feature-hunt/pull/93/files

@etracey7 updated **backend**/auth_controller.py (not backend-new!)

Try making a pull request and see if your tests work with her updates.

**Comment by snapcat** [comment]
Discussion: https://github.com/CSC510-Group-25/feature-hunt/pull/119#issuecomment-968385183
