### ISSUE TITLE
Resolve Pylint Errors and cleanup backend code

### ISSUE THREAD

**Issue by peeyush10234** [CSC510-Group-25/feature-hunt#123]
Resolve Pylint Errors and cleanup backend code

**Comment by snapcat** [comment]
Discussed over discord!

**Comment by snapcat** [comment]
Discord:

> Leila Moran — 11/04/2021
> https://github.com/CSC510-Group-25/feature-hunt/issues/123
> 
> Is this done?
> 
> Peeyush — 11/04/2021
> Yes
