### ISSUE TITLE
MongoDB: collections named "user" and "users", both used in backend and backend-new files

### ISSUE THREAD

**Issue by snapcat** [CSC510-Group-25/feature-hunt#129]
"user" collection used in backend-new/db_init.py

"users" collection used in backend/app/__init__.py

This may cause significant confusion down the road if left unaddressed.

Suggested fix: delete or rename one of the collections and/or update the relevant files.

**Comment by peeyush10234** [comment]
changed records = db.user  to db.users  in db_init.py file.

**Comment by snapcat** [comment]
Resolved
