### ISSUE TITLE
Implement login (React)

### ISSUE THREAD

**Issue by snapcat** [CSC510-Group-25/feature-hunt#20]

**Comment by etracey7** [comment]
Added the signin form, dashboard and edit tag functionality. To Do:

- [ ] Connect user to project in database
- [ ] Apply logic so user can only add to their own project features
- [ ] Add Authentication of some sort 
- [ ] change theme to be consistent colors
- [ ] format header to handle button and "Your Projects"

**Comment by snapcat** [comment]
Discussions: 

See https://github.com/CSC510-Group-25/feature-hunt/pull/93#issuecomment-968369480

See also: https://github.com/CSC510-Group-25/feature-hunt/pull/79#issuecomment-968365783
