### ISSUE TITLE
Add test case for addProjectDetail Function

### ISSUE THREAD

**Issue by peeyush10234** [CSC510-Group-25/feature-hunt#58]

**Comment by peeyush10234** [comment]
Test case added

**Comment by snapcat** [comment]
Discussion:

> Leila Moran — 11/04/2021
> @ Peeyush 
> https://github.com/CSC510-Group-25/feature-hunt/issues/8
> https://github.com/CSC510-Group-25/feature-hunt/issues/117
> 
> We good on these? We have heroku and netlify.
> 
> Peeyush — 11/04/2021
> yes i will close these with comments
> 
> Leila Moran— 11/04/2021
> I got more for you! @ Peeyush 
> 
> https://github.com/CSC510-Group-25/feature-hunt/issues/59
> https://github.com/CSC510-Group-25/feature-hunt/issues/58
> 
> Aaaand a thing for @ jhnguye4 to close with comments: https://github.com/CSC510-Group-25/feature-hunt/issues/17
