### ISSUE TITLE
Host website on Cloud

### ISSUE THREAD

**Issue by snapcat** [CSC510-Group-25/feature-hunt#8]
(no comment)

https://github.com/shahrk/feature-hunt/issues/34#issue-1009976973

**Comment by peeyush10234** [comment]
Backend deployed on Heroku
Frontend deployed on netlify

**Comment by snapcat** [comment]
Discussion:

> Leila Moran — 11/04/2021
> Are these done?
> 
> https://github.com/CSC510-Group-25/feature-hunt/issues/57
> https://github.com/CSC510-Group-25/feature-hunt/issues/56
> 
> Peeyush — 11/04/2021
> yup
> 
> Leila Moran — 11/04/2021
> Would you mind leaving comments on them and closing?
> Peeyush — 11/04/2021
> yeah ok

> Leila Moran — 11/04/2021
> @ Peeyush 
> https://github.com/CSC510-Group-25/feature-hunt/issues/8
> https://github.com/CSC510-Group-25/feature-hunt/issues/117
> 
> We good on these? We have heroku and netlify.
> 
> Peeyush — 11/04/2021
> yes i will close these with comments
> 
> Leila Moran— 11/04/2021
> I got more for you! @ Peeyush 
> 
> https://github.com/CSC510-Group-25/feature-hunt/issues/59
> https://github.com/CSC510-Group-25/feature-hunt/issues/58
> 
> Aaaand a thing for @ jhnguye4 to close with comments: https://github.com/CSC510-Group-25/feature-hunt/issues/17
